### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by livejamie** [TwidereProject/TwidereX-Android#3]
Using the Galaxy Fold 2 the app crashes on startup in both folded and unfolded view.

I sent a crash report.

**Comment by NovaMoon** [comment]
Getting a crash on startup as well. 

`
time: 1607133282663
msg: java.lang.ClassCastException: java.lang.String cannot be cast to androidx.compose.ui.text.TtsAnnotation
stacktrace: java.lang.ClassCastException: java.lang.String cannot be cast to androidx.compose.ui.text.TtsAnnotation
	at androidx.compose.ui.text.platform.AndroidAccessibilitySpannableStringKt.toAccessibilitySpannableString(AndroidAccessibilitySpannableString.kt:60)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.populateAccessibilityNodeInfoProperties(AndroidComposeViewAccessibilityDelegateCompat.kt:235)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.kt:184)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.access$createNodeInfo(Unknown Source:0)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$MyNodeProvider.createAccessibilityNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.kt:1600)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1346)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1076)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:341)
	at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:75)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)`
Android 10

**Comment by Tlaster** [comment]
Thanks for reporting this issue.
Have you turn on any accessibility function on the phone?

**Comment by livejamie** [comment]
I have some services like Bitwarden, SDMaid, EasyJoin that are turned on.

**Comment by Tlaster** [comment]
I've addressed the issue, seems like it's another bug from Google.
I'm working on a workaround, meanwhile, I've reported it to Google at kotlin slack

**Comment by Tlaster** [comment]
This should be fixed after 1.0.0-alpha07, but accessibility function like screen reader might not work ATM.
Related: https://issuetracker.google.com/issues/175141969
