### ISSUE TITLE
[Bug] IndexOutOfBoundsException from scrolling super fast

### ISSUE THREAD

**Issue by TacoTheDank** [TwidereProject/TwidereX-Android#52]
# Bug Report

## Environment

Network type:

- [x] Cellular
- [ ] Wi-Fi

## Build Variant

- [x] Google Play
- [ ] FDroid

App version: 

1.1.0-beta01 (30)

### Steps to reproduce
Every time I would view a piece of media (image, video, etc) in a post's reply section (I guess referred to as the twitter "thread"), closing it would reset me back to the OP post (I'd say this is unwanted behavior). I decided to start scrolling super fast to get back to where I was and then this happened.

Here's the stack trace I caught using my [Scoop](https://github.com/TacoTheDank/Scoop) app.
```
FATAL EXCEPTION: main
Process: com.twidere.twiderex, PID: 7539
java.lang.IndexOutOfBoundsException: Index: 96, Size: 51
	at androidx.paging.PagePresenter.checkIndex(PagePresenter.kt:45)
	at androidx.paging.PagePresenter.get(PagePresenter.kt:55)
	at androidx.paging.PagingDataDiffer.get(PagingDataDiffer.kt:249)
	at com.twidere.twiderex.component.lazy.LazyPagingItems.get(LazyPagingItems.kt:116)
	at com.twidere.twiderex.component.lazy.LazyStatusListKt$statusesIndexed$2.invoke(LazyStatusList.kt:55)
	at com.twidere.twiderex.component.lazy.LazyStatusListKt$statusesIndexed$2.invoke(LazyStatusList.kt:54)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:149)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.foundation.lazy.LazyListScopeImpl$items$1$1.invoke(LazyDsl.kt:175)
	at androidx.compose.foundation.lazy.LazyListScopeImpl$items$1$1.invoke(LazyDsl.kt:175)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:193)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
	at androidx.compose.foundation.lazy.LazyListItemContentFactory$CachedItemContent$content$1.invoke(LazyListItemContentFactory.kt:107)
	at androidx.compose.foundation.lazy.LazyListItemContentFactory$CachedItemContent$content$1.invoke(LazyListItemContentFactory.kt:104)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1.invoke(SubcomposeLayout.kt:167)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1.invoke(SubcomposeLayout.kt:167)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3418)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:2600)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:348)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:693)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3024)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3024)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:304)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcomposeInto(SubcomposeLayout.kt:184)
	at androidx.compose.ui.layout.SubcomposeLayoutState.access$subcomposeInto(SubcomposeLayout.kt:100)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:160)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:158)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.withNoObservations(SnapshotStateObserver.kt:137)
	at androidx.compose.ui.node.OwnerSnapshotObserver.withNoSnapshotReadObservation$ui_release(OwnerSnapshotObserver.kt:49)
	at androidx.compose.ui.node.LayoutNode.withNoSnapshotReadObservation$ui_release(LayoutNode.kt:1086)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:158)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:152)
	at androidx.compose.foundation.lazy.LazyMeasuredItemProvider.getAndMeasure-ZjPyQlc(LazyMeasuredItemProvider.kt:47)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-nqpP7js(LazyListMeasure.kt:134)
	at androidx.compose.foundation.lazy.LazyListKt$LazyList$1.invoke-0kLqBqw(LazyList.kt:145)
	at androidx.compose.foundation.lazy.LazyListKt$LazyList$1.invoke(LazyList.kt:95)
	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:212)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(Padding.kt:415)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:210)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:97)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:96)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1714)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:116)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:63)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:96)
	at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$ui_release(LayoutNode.kt:1202)
	at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$ui_release$default(LayoutNode.kt:1200)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-0kLqBqw(MeasureAndLayoutDelegate.kt:172)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$doRemeasure-0kLqBqw(MeasureAndLayoutDelegate.kt:39)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:211)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:448)
	at androidx.compose.ui.node.LayoutNode.forceRemeasure(LayoutNode.kt:1220)
	at androidx.compose.foundation.lazy.LazyListState.onScroll$foundation_release(LazyListState.kt:235)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:139)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:139)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:134)
	at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll(Scrollable.kt:349)
	at androidx.compose.foundation.gestures.ScrollableKt.dragForEachGesture$mainDragCycle$touchDragTick(Scrollable.kt:235)
	at androidx.compose.foundation.gestures.ScrollableKt.access$dragForEachGesture$mainDragCycle$touchDragTick(Scrollable.kt:1)
	at androidx.compose.foundation.gestures.ScrollableKt$dragForEachGesture$mainDragCycle$2$1$dragTick$1.invoke(Scrollable.kt:252)
	at androidx.compose.foundation.gestures.ScrollableKt$dragForEachGesture$mainDragCycle$2$1$dragTick$1.invoke(Scrollable.kt:250)
	at androidx.compose.foundation.gestures.DragGestureDetectorKt.verticalDrag-jO51t88(DragGestureDetector.kt:808)
	at androidx.compose.foundation.gestures.DragGestureDetectorKt$verticalDrag$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:396)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:293)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:421)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:318)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:331)
	at androidx.compose.ui.input.pointer.Node.dispatchToPointerInputFilter(HitPathTracker.kt:360)
	at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:308)
	at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:304)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchChanges(HitPathTracker.kt:179)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:111)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-gBdvCQM(PointerInputEventProcessor.kt:80)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:696)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:770)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4038)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:728)
	at android.view.View.dispatchPointerEvent(View.java:14636)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6582)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6360)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5971)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6028)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9032)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8889)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8842)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9169)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9109)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9196)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by TacoTheDank** [comment]
Thanks :)
