### ISSUE TITLE
[Bug] Crash when trying to login with Custom Twitter Key

### ISSUE THREAD

**Issue by Furikuda** [TwidereProject/TwidereX-Android#84]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [X] Wi-Fi

## Build Variant

- [ ] Google Play
- [X] FDroid

App version: 
1.0.6

### Steps to reproduce

Try to login using the Custom Twitter Key flow, app crashes

### Actual Behavior

After copy pasting my API key & API secret key in the appropriate fields the app crashes. Here's the relevant logcat:
```
05-05 09:34:09.729  1832  6412 I okhttp.OkHttpClient: --> POST https://api.twitter.com/oauth/request_token
05-05 09:34:09.730  1832  6412 I okhttp.OkHttpClient: Content-Type: application/x-www-form-urlencoded
05-05 09:34:09.730  1832  6412 I okhttp.OkHttpClient: Content-Length: 18
05-05 09:34:09.730  1832  6412 I okhttp.OkHttpClient: Authorization: OAuth oauth_consumer_key="Hc9oqrD76pdXXXXXXXXXXXXX", oauth_nonce="2kHPqklPHHTaNF5TtFNHISaw09lXXXXXXXXXXXXXXX", oauth_signature="4XXXXXXXXXXXX%2BXXXXXXXXXXXX4%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1620200049",  oauth_version="1.0"
05-05 09:34:09.731  1832  6412 I okhttp.OkHttpClient: oauth_callback=oob
05-05 09:34:09.731  1832  6412 I okhttp.OkHttpClient: --> END POST (18-byte body)
05-05 09:34:09.817  1832  1832 E AndroidRuntime: FATAL EXCEPTION: main
05-05 09:34:09.817  1832  1832 E AndroidRuntime: Process: com.twidere.twiderex, PID: 1832
05-05 09:34:09.817  1832  1832 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10240; index=-2
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.SlotTableKt.groupSize(SlotTable.kt:2558)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.SlotTableKt.access$groupSize(SlotTable.kt:1)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.SlotReader.groupSize(SlotTable.kt:596)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2215)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2499)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2625)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:406)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:724)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:100)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:437)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:411)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:112)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:43)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:72)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:727)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-05 09:34:09.817  1832  1832 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-05 09:34:09.820  1095  6414 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-05 09:34:09.820  1095  6333 W ActivityTaskManager:   Force finishing activity com.twidere.twiderex/.TwidereXActivity
05-05 09:34:09.844  1832  1832 I Process : Sending signal. PID: 1832 SIG: 9
05-05 09:34:09.863  1095  2334 I WindowManager: WIN DEATH: Window{4097029 u0 com.twidere.twiderex/com.twidere.twiderex.TwidereXActivity EXITING}
```

###  Expected behavior

The app doesn't crash and logs in to Twitter

**Comment by Tlaster** [comment]
Seems like a Jetpack Compose's bug

**Comment by Tlaster** [comment]
It seems like working after 1.1.0, can you please try the 1.1.0 version?

**Comment by Furikuda** [comment]
Can you have fdroid build 1.1.0?
From https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.twidere.twiderex.yml  it seems that the current process to detect a new version is broken, as https://raw.githubusercontent.com/TwidereProject/TwidereX-Android/release/versions.gradle does not exist

**Comment by Tlaster** [comment]
oops, on it

**Comment by Furikuda** [comment]
will wait for the new version to hit the repo and report back

**Comment by Furikuda** [comment]
I confirm the app does not crash, although I end up on the twitter page to log in with my password, and I wonder if that's intended

**Comment by Tlaster** [comment]
Yes, this is intended behavior.
