### ISSUE TITLE
[Bug] Crash when opening app

### ISSUE THREAD

**Issue by Furikuda** [TwidereProject/TwidereX-Android#91]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [x] Wi-Fi

## Build Variant

- [ ] Google Play
- [x] FDroid

App version: 
1.0.6

## Bug Info
The app crashes when opening it. It was working fine up until today (I have not updated android since)

### Steps to reproduce
Open the app

### Actual Behavior

App just crashes with the following logs
```
05-11 12:10:48.400 25861 25861 E AndroidRuntime: FATAL EXCEPTION: main
05-11 12:10:48.400 25861 25861 E AndroidRuntime: Process: com.twidere.twiderex, PID: 25861
05-11 12:10:48.400 25861 25861 E AndroidRuntime: java.lang.IllegalArgumentException: 0 was already used with subcompose during this measuring pass
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:137)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyMeasuredItemProvider.getAndMeasure-ZjPyQlc(LazyMeasuredItemProvider.kt:48)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-nqpP7js(LazyListMeasure.kt:134)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$LazyList$1.invoke-0kLqBqw(LazyList.kt:144)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$LazyList$1.invoke(LazyList.kt:94)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:212)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(Padding.kt:415)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:210)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:63)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1194)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:133)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:647)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:156)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:63)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1194)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:317)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:230)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:224)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:917)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:901)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1709)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:116)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:56)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:901)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:889)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:108)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeApparentToRealOffset-aW-9-wM(Placeable.kt:300)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:191)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:129)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.replace(OuterMeasurablePlaceable.kt:140)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.replace$ui_release(LayoutNode.kt:787)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:219)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:435)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:568)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21186)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21186)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21186)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21186)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-11 12:10:48.400 25861 25861 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-11 12:10:48.404  1095 17762 W ActivityTaskManager:   Force finishing activity com.twidere.twiderex/.TwidereXActivity
05-11 12:10:48.404  1095 28880 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-11 12:10:48.425 25861 25861 I Process : Sending signal. PID: 25861 SIG: 9
```

###  Expected behavior

Can use the app

**Comment by Tlaster** [comment]
Seems like another Compose bug, I remember this was fixed after 1.1.0, can you please try the 1.1.0 version?

**Comment by Furikuda** [comment]
still anxiously waiting for it to show up on the fdroid repo :)

**Comment by Tlaster** [comment]
Closing the issue, reopen if you're still encountering the same issue.
