### ISSUE TITLE
[Bug] Crash when trying to log into Twitter

### ISSUE THREAD

**Issue by joseph-20** [TwidereProject/TwidereX-Android#94]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [x] Wi-Fi

## Build Variant

- [ ] Google Play
- [x] FDroid

App version: 
1.1.0

## Bug Info
The app crashes when trying to log into Twitter via the normal login (not the API login, basically)

### Steps to reproduce
Open the app, tap on "Sign in with Twitter"

### Actual Behavior
The app shows the loading animation and then crashes, logs below
```
FATAL EXCEPTION: main
Process: com.twidere.twiderex, PID: 9988
java.lang.IllegalStateException: LayoutCoordinates androidx.compose.ui.node.InnerPlaceable@54eb3c5 is not attached!
	at androidx.compose.ui.node.LayoutNodeWrapper.localBoundingBoxOf(LayoutNodeWrapper.kt:365)
	at androidx.compose.ui.layout.LayoutCoordinates$DefaultImpls.localBoundingBoxOf$default(LayoutCoordinates.kt:91)
	at androidx.compose.ui.semantics.NodeLocationHolder.<init>(SemanticsSort.kt:70)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:45)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:53)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:53)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:53)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:53)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:53)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:53)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:53)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds(SemanticsSort.kt:53)
	at androidx.compose.ui.semantics.SemanticsSortKt.findOneLayerOfSemanticsWrappersSortedByBounds$default(SemanticsSort.kt:27)
	at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui_release(SemanticsNode.kt:178)
	at androidx.compose.ui.semantics.SemanticsNode.getChildren(SemanticsNode.kt:225)
	at androidx.compose.ui.semantics.SemanticsNode.getChildrenSortedByBounds$ui_release(SemanticsNode.kt:210)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.populateAccessibilityNodeInfoProperties(AndroidComposeViewAccessibilityDelegateCompat.android.kt:298)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:273)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.access$createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:96)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$MyNodeProvider.createAccessibilityNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2141)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:6565)
	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:23642)
	at android.view.View.createAccessibilityNodeInfo(View.java:6551)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
	at android.view.View.onInitializeAccessibilityEventInternal(View.java:6505)
	at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:23554)
	at androidx.core.view.AccessibilityDelegateCompat.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:257)
	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:76)
	at android.view.View.onInitializeAccessibilityEvent(View.java:6491)
	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6358)
	at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:23493)
	at androidx.core.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:196)
	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:113)
	at android.view.View.sendAccessibilityEventUnchecked(View.java:6341)
	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:7493)
	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:7519)
	at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:6631)
	at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:6815)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3099)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3099)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3099)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3099)
	at android.view.View.notifySubtreeAccessibilityStateChangedIfNeeded(View.java:9497)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4478)
	at android.view.ViewGroup.addView(ViewGroup.java:4258)
	at android.view.ViewGroup.addView(ViewGroup.java:4198)
	at android.view.ViewGroup.addView(ViewGroup.java:4171)
	at androidx.compose.ui.platform.AndroidComposeView.getAndroidViewsHandler$ui_release(AndroidComposeView.android.kt:253)
	at androidx.compose.ui.platform.AndroidComposeView.addAndroidView(AndroidComposeView.android.kt:429)
	at androidx.compose.ui.viewinterop.AndroidViewHolder$layoutNode$1$3.invoke(AndroidViewHolder.android.kt:211)
	at androidx.compose.ui.viewinterop.AndroidViewHolder$layoutNode$1$3.invoke(AndroidViewHolder.android.kt:210)
	at androidx.compose.ui.node.LayoutNode.attach$ui_release(LayoutNode.kt:329)
	at androidx.compose.ui.node.LayoutNode.attach$ui_release(LayoutNode.kt:322)
	at androidx.compose.ui.node.LayoutNode.insertAt$ui_release(LayoutNode.kt:217)
	at androidx.compose.ui.node.UiApplier.insertBottomUp(UiApplier.android.kt:32)
	at androidx.compose.ui.node.UiApplier.insertBottomUp(UiApplier.android.kt:22)
	at androidx.compose.runtime.ComposerImpl$createNode$3.invoke(Composer.kt:1368)
	at androidx.compose.runtime.ComposerImpl$createNode$3.invoke(Composer.kt:1363)
	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:2697)
	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:2694)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:562)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:708)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:2914)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:2914)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:409)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcomposeInto(SubcomposeLayout.kt:184)
	at androidx.compose.ui.layout.SubcomposeLayoutState.access$subcomposeInto(SubcomposeLayout.kt:100)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:160)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:158)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.withNoObservations(SnapshotStateObserver.kt:137)
	at androidx.compose.ui.node.OwnerSnapshotObserver.withNoSnapshotReadObservation$ui_release(OwnerSnapshotObserver.kt:49)
	at androidx.compose.ui.node.LayoutNode.withNoSnapshotReadObservation$ui_release(LayoutNode.kt:1054)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:158)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:152)
	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:303)
	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:230)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:224)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:902)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:886)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:56)
	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:886)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:874)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:108)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:149)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:191)
	at androidx.compose.foundation.layout.BoxKt.placeInBox(Box.kt:182)
	at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:1)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:122)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:121)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:902)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:886)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:56)
	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:886)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:874)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:108)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:381)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:254)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:215)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:214)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:103)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:191)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$measure$1$1.placeChildren(DelegatingLayoutNodeWrapper.kt:115)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:103)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:381)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:254)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:215)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:214)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:103)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:149)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:191)
	at androidx.compose.foundation.layout.BoxKt.placeInBox(Box.kt:182)
	at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:1)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:122)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:121)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:902)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:886)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:56)
	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:886)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:874)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:108)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:191)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$measure$1$1.placeChildren(DelegatingLayoutNodeWrapper.kt:115)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:103)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place(Placeable.kt:355)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place$default(Placeable.kt:179)
	at androidx.compose.foundation.layout.PaddingValuesModifier$measure$2.invoke(Padding.kt:420)
	at androidx.compose.foundation.layout.PaddingValuesModifier$measure$2.invoke(Padding.kt:419)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:103)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:149)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:191)
	at androidx.compose.foundation.layout.BoxKt.placeInBox(Box.kt:182)
	at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:1)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$5.invoke(Box.kt:163)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$5.invoke(Box.kt:159)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:902)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:886)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:56)
	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:886)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:874)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:108)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:149)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:191)
	at androidx.compose.foundation.layout.BoxKt.placeInBox(Box.kt:182)
	at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:1)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$5.invoke(Box.kt:163)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$5.invoke(Box.kt:159)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:902)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:886)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:56)
	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:886)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:874)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:108)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:381)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:254)
	at androidx.compose.ui.graphics.BlockGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:158)
	at androidx.compose.ui.graphics.BlockGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:157)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:103)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:149)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:191)
	at androidx.compose.foundation.layout.BoxKt.placeInBox(Box.kt:182)
	at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:1)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:122)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:121)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:902)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:886)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:56)
	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:886)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:874)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:108)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative(Placeable.kt:347)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:167)
	at androidx.compose.foundation.layout.FillModifier$measure$1.invoke(Size.kt:655)
	at androidx.compose.foundation.layout.FillModifier$measure$1.invoke(Size.kt:654)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:103)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:149)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:191)
	at androidx.compose.foundation.layout.BoxKt.placeInBox(Box.kt:182)
	at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:1)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$5.invoke(Box.kt:163)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$5.invoke(Box.kt:159)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:902)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:886)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1787)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:116)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:56)
	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:886)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:874)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:108)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:358)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:149)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.replace(OuterMeasurablePlaceable.kt:161)
	at androidx.compose.ui.node.LayoutNode.replace$ui_release(LayoutNode.kt:791)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:220)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:506)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:655)
	at android.view.View.draw(View.java:17192)
	at android.view.View.updateDisplayListIfDirty(View.java:16171)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16134)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16134)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16134)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16134)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

###  Expected behavior
The login web page should appear

**Comment by Tlaster** [comment]
Seems like another Jetpack Compose bug, have you turn on any accessibility feature on your phone?

**Comment by joseph-20** [comment]
Yes I did, I enabled Bitwarden's accessibility service

**Comment by joseph-20** [comment]
Ok so, disabling the accessibilty service does the job, so a quick workaround is:
1.  Disable accessibilty acces
2. Tap on "Sign in with Twitter"
3. Re-enable accessibility serivce and continue through the sign in process

So basically, the crash only occurs if the accessibility service is active and you try to sign in, but if you disable it, let the app load the sign in page and then re-enable it then it's all good and everything works just fine

**Comment by Tlaster** [comment]
Got the issue tracker from google: https://issuetracker.google.com/issues/187101535

**Comment by Tlaster** [comment]
Mark as fixed since the issue tracker from google was mark as fixed
